### ISSUE TITLE
[Bug] Character lvl or experience don't show on character screen while playing. 

### ISSUE THREAD

**Issue by Epirus29** [LLAMARPG/game#21]
**A clear and concise description of what the bug is:**
I killed a lot of things and it said I was lvl 1 with 0 exp.  When I logged out and back in it showed my character as lvl 42 with ~800xp

**Steps to reproduce the behavior, if necessary:**
Kill mobs and press "C" and you will see no progress.  Quit the game and come back in and you will see your character lvl and xp.

**Comment by Warren1001** [comment]
fixed in 0.1.0
