### ISSUE TITLE
[Bug] Gold doesn't save to character after quitting

### ISSUE THREAD

**Issue by Epirus29** [LLAMARPG/game#22]
I received gold from mobs I killed and it showed in my inventory.  When I quit the game and came back in it said I had 0 gold.

**Comment by Warren1001** [comment]
weird, i remember testing gold given from quest and it saved. maybe the bug is specific to gold rewarded in combat (only awards client-side maybe?)

**Comment by Warren1001** [comment]
i don't remember fixing it but i tested it and it was fine for me on the latest dev build, so maybe its fixed, maybe its not, you can test again once the build goes live sometime tomorrow

**Comment by Vvnguyen25** [comment]
The bug has not been fixed :( Had 3 gold in inventory and when I left it was all gone:

Before Quitting
![image](https://github.com/LLAMARPG/game/assets/172426161/829efa25-2635-4bdb-a615-71c449c8495b)

After Quitting:
![image](https://github.com/LLAMARPG/game/assets/172426161/c37859a6-a719-4392-a2d5-a722edcd2055)

**Comment by Warren1001** [comment]
i never got around to pushing the build to steam (once i do, the client will have a version in the settings menu so that everyone can keep up with what has been fixed in which version).

this should be fixed in 0.1.0 in all my testing today, which isnt on steam yet
