### ISSUE TITLE
[Feature] Full Inventory Notice When Looting

### ISSUE THREAD

**Issue by Epirus29** [LLAMARPG/game#25]
If your inventory is full it doesn't warn you and you can pick up stuff from a mob but it won't go into your inventory. Also would be nice if you could open inventory to compare/remove stuff before picking up loot.

**Comment by Warren1001** [comment]
yeah, the design for this hasnt been figured out yet. also don't think you can get rid of items either. maybe dropping them into the world will delete them, but theres not a clear indication of this which should probably be added too

**Comment by Warren1001** [comment]
i forced the client to open the inventory when it tries to loot an item and the inventory is full
@MrLlamaSC do you want some other way to indicate to the player that their inventory is full?

**Comment by Vvnguyen25** [comment]
The client forced open my inventory when my inventory wasn't full. Even when the inventory is full, I'm unable to discard any items from my inventory OR loot any of the monster items:

![image](https://github.com/LLAMARPG/game/assets/172426161/4e9fb365-5b2d-4ac4-a6c8-32bf7e73c4ab)

**Comment by Warren1001** [comment]
the above bug was due to improper inventory syncing which was fixed. the original bug report should be fixed
