### ISSUE TITLE
[Bug] Chest/box at sits at wrong layer

### ISSUE THREAD

**Issue by red-squids** [LLAMARPG/game#32]
**A clear and concise description of what the bug is:**
In linux build chest or box at -669.26, -1307.00 appears above character sprite despite having a block action.

**Steps to reproduce the behavior, if necessary:**
walk beneath

![image](https://github.com/LLAMARPG/game/assets/67482591/3c11866e-44a3-4507-b2ed-0e07d9106fd7)

**Comment by Warren1001** [comment]
let's keep all the layering issues in one thread #26 that way they arent filling up the issues (theres a lot of layering issues)
