### ISSUE TITLE
[Bug] Character sprite falls beneath bridge at town entrace

### ISSUE THREAD

**Issue by red-squids** [LLAMARPG/game#33]
**A clear and concise description of what the bug is:**
In linux build character sprite falls beneath bridge abruptly when traveling either direction.

**Steps to reproduce the behavior, if necessary:**
Occurs when exiting or entering town.

![image](https://github.com/LLAMARPG/game/assets/67482591/cb947976-32fc-4d5d-9abc-c67f9fa4d9fd)

**Comment by Warren1001** [comment]
let's keep all the layering issues in one thread #26 that way they arent filling up the issues (theres a lot of layering issues)
