### ISSUE TITLE
[Feature] Dropped items not recoverable/no warning given

### ISSUE THREAD

**Issue by red-squids** [LLAMARPG/game#34]
**Explain what you think should be changed, altered, added, or removed and why:**
A dropped item vanishes and cant be recovered presently, if dropping destroys the item is intentional a warning would be helpful

**Comment by Warren1001** [comment]
yeah like mentioned in #25 we havent figured out a system for full inventory or getting rid of items yet. the throwing them off into the world is just a temp solution for testing until llama figures out something

**Comment by Warren1001** [comment]
added in 0.1.0

**Comment by Warren1001** [comment]
now live

**Comment by Warren1001** [comment]
oh forgot to mention, it uses the keybind listed in the master doc, ctrl + shift + right click deletes an item. it is now considered a bug to drop the item off the inventory and it disappears from your inventory clientside
