### ISSUE TITLE
[Bug] Unlimited gold through memory modification

### ISSUE THREAD

**Issue by red-squids** [LLAMARPG/game#35]
**A clear and concise description of what the bug is:**
Amount of gold held in inventory can be deduced and modified by memory modification

**Steps to reproduce the behavior, if necessary:**
1. search for value of currently held gold in memory space
2. gain gold, search for updated value
3. eliminate dynamic values
4. modify remaining value
5. relog and value has changed.

![image](https://github.com/LLAMARPG/game/assets/67482591/404d817e-4309-4e26-aae3-b70978d231b6)

**Comment by Warren1001** [comment]
if someone wants to cheat in singleplayer, i think its fine. they could just mod the game themselves to make everything give a million gold.
