### ISSUE TITLE
[Bug] - Items of Enemy displays behind Enemy Sprite.

### ISSUE THREAD

**Issue by Vvnguyen25** [LLAMARPG/game#37]
Items of Enemy displays behind Enemy Sprite.

Steps to reproduce: Get into a battle with an enemy and select the Items icon.

Expected results: The items should display on top of the enemy sprite

![image](https://github.com/LLAMARPG/game/assets/172426161/2e1fa272-dc88-4b31-9d4a-5cf58d4786cd)

**Comment by Warren1001** [comment]
intended, that button is only a dev feature and not going to be available in the release of the actual game
