### ISSUE TITLE
[Bug] - Upon Quitting and Rejoining, player health is restored, but when entering in a battle health is at zero.

### ISSUE THREAD

**Issue by Vvnguyen25** [LLAMARPG/game#38]
Logged out after being defeated in battle with zero HP. When player logged back in, HP is restore on the character screen. When encountering an enemy, the HP is still at zero.

Steps to recreate: 

1. Get defeated by an enemy and exit the battle. 
2. Quit to main menu and select the character.
3.  Log back in and check character health.
4. Get yourself into a battle and check character health.

When logging back in:

![image](https://github.com/LLAMARPG/game/assets/172426161/fd42d11f-8356-4ff1-98ae-9e270d49db9f)

When entering in a battle:

![image](https://github.com/LLAMARPG/game/assets/172426161/f42a24ea-6c0d-47b0-b2fb-3715c67e6cf6)

**Comment by Warren1001** [comment]
related issue: #1

**Comment by Warren1001** [comment]
fixed in 0.1.0

**Comment by Warren1001** [comment]
not gonna mark as completed anymore until the fix is actually live, gonna just add the tag fixed-on-dev instead and then mark as completed when its live since this repo is publically visible

**Comment by Warren1001** [comment]
now live
