### ISSUE TITLE
[Bug]  When Items are looted from monsters, they are not appearing in the player's inventory when slots are open

### ISSUE THREAD

**Issue by Vvnguyen25** [LLAMARPG/game#39]
When a player has  random open slots in their inventory and they defeat an enemy to loot the items, the items are not given in the players inventory.

Steps to recreate:

1. Have an inventory that is almost full but has item slots open that aren't toward the bottom of the inventory.
2. Defeat a monster and loot the items.
3.  Items do not appear in the inventory.

Inventory before battle:

![image](https://github.com/LLAMARPG/game/assets/172426161/03cec212-f8b1-4175-a011-e48440f11570)

Items from Monster:

![image](https://github.com/LLAMARPG/game/assets/172426161/74dc5823-7cc8-4304-982d-7e7432bf5703)

Inventory after battle:

![image](https://github.com/LLAMARPG/game/assets/172426161/26484a8d-0ea3-401f-88df-616c15da025c)

Expected Results: Items should appear in the first available slot 

**Upload or paste the contents of the log file, if necessary, which can be found in the [Godot user folder](https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html#accessing-persistent-user-data-user) `user://llamarpg_game/logs/dev.log`.**

**Comment by Vvnguyen25** [comment]
Items are not appearing at all when looted from monsters actually. I have the last spots open as well an nothing is being given.

**Comment by Vvnguyen25** [comment]
Logged out and logged back in to see multiple items from the inventory disappearing:

![image](https://github.com/LLAMARPG/game/assets/172426161/eb663868-740a-411d-826e-bbdf2801f095)

**Comment by Vvnguyen25** [comment]
Issue is still happening with many item slots open:

![image](https://github.com/LLAMARPG/game/assets/172426161/e1509a57-c38b-4a06-afdf-8941b6bdb861)

![image](https://github.com/LLAMARPG/game/assets/172426161/e7858d6e-27ad-4e00-b529-2737d2851dfc)

**Comment by Warren1001** [comment]
i learned what causes this. i never gave the items to the player server side lol

**Comment by Warren1001** [comment]
also couldn't recreate this, let me know if its fixed in the current live version that just went out

**Comment by Warren1001** [comment]
i think this got fixed the same time the other weird item poofing glitch got fixed, closing for now, reopen if you can recreate it
