### ISSUE TITLE
[Bug]  BIG BUG! Equipping items and exiting the game will have the replaced item and the equipped item disappear

### ISSUE THREAD

**Issue by Vvnguyen25** [LLAMARPG/game#47]
When equipping items from your inventory, both items that was replaced and equipped will disappear upon logging out and logging back in.

Before

![image](https://github.com/LLAMARPG/game/assets/172426161/1cef55af-5e27-49ea-9928-8e203000b84b)

After

![image](https://github.com/LLAMARPG/game/assets/172426161/40ed6a74-ae68-48dd-978b-0530806cfe32)

Before

![image](https://github.com/LLAMARPG/game/assets/172426161/ca73d250-1745-4194-a24f-6152d2ca9a20)

After

![image](https://github.com/LLAMARPG/game/assets/172426161/96f0b104-e875-4ccd-9dba-0e07d4935f93)

**Comment by Vvnguyen25** [comment]
Per Alex, to send to you Warren.

Also, when getting items from the inventory to your personal inventory or equipping them. The items also disappear upon logging out.

Stash:
![image](https://github.com/LLAMARPG/game/assets/172426161/3fc4d702-adaf-4670-a349-d19628930a8a)

Took 3 items out:
![image](https://github.com/LLAMARPG/game/assets/172426161/cc1710a0-0ebc-4ef0-affc-ed342a63d953)

Equipped:
![image](https://github.com/LLAMARPG/game/assets/172426161/3d8d409a-825e-47d4-b028-ae1b1836532a)

Upon Logging in, Items were still in stash and not equipped to character:
![image](https://github.com/LLAMARPG/game/assets/172426161/4cd97846-00f3-445e-ae49-cfe8aae74af1)

**Comment by Warren1001** [comment]
whatever causes this likely causes #39 too

**Comment by Vvnguyen25** [comment]
Looks like exiting out of the game completely instead of going to the main menu will bring back the inventory. So it maybe a server sync issue.

**Comment by Warren1001** [comment]
i'm having trouble recreating this, are there any errors? check the dev or godot log for potential errors

**Comment by Vvnguyen25** [comment]
its still happening to me, I am equipping items from my inventory and then quitting the game to main menu. Then I select the character and log back into the game and items are gone.

How do I check dev or godot log?

**Comment by Warren1001** [comment]
theres instructions on how to do that when you create an issue in the template given

its in `%appdata%/Godot/app_userdata/llamarpg_game/logs`

the issue may be fixed in the current dev version so i guess we'll just wait for that to go live to see if you still get it. i've done exactly what you say in every way i can imagine and the item is always there for me

**Comment by Vvnguyen25** [comment]
Issue isn't happening anymore since the latest update. Closing this issue
