### ISSUE TITLE
[Bug] Need to have a character limit for chat messages. I was able to enter over 10,000 characters into a chat message and the game froze

### ISSUE THREAD

**Issue by Vvnguyen25** [LLAMARPG/game#48]
Press enter to open chat.

Type out over 10,000 characters into the message and press enter.

Game will freeze up causing the game to crash.

Need to implement a character limit for sending messages to prevent messages more than X amount from being entered.

![image](https://github.com/LLAMARPG/game/assets/172426161/2bc40a4b-31b6-483f-bb35-edd00a83ef5a)

**Comment by Warren1001** [comment]
LOL good call

**Comment by Warren1001** [comment]
fixed in 0.1.0

**Comment by Warren1001** [comment]
now live
