### ISSUE TITLE
[Feature] Prevent chat spam/mature language filter

### ISSUE THREAD

**Issue by Vvnguyen25** [LLAMARPG/game#49]
A user can constantly spam messages in chat. Need to be able to limit the user from spamming chat messages over and over again.

**Comment by Vvnguyen25** [comment]
Also maybe implement a language filter as well

**Comment by Warren1001** [comment]
ya i plan to have a filter and add moderation features/banning from the server as currently there is no way to prevent someone from just going wild and spewing a lot of garbage

**Comment by Warren1001** [comment]
added in 0.3.0

**Comment by Warren1001** [comment]
0.3.0 is live
