### ISSUE TITLE
[Bug] Spam clicking the Play Button in battle will have the sprites of both characters mess up

### ISSUE THREAD

**Issue by Vvnguyen25** [LLAMARPG/game#50]
During combat, when spam clicking the Play Button to get through battle quicker. The attacking sprites will be messaged up causing them to move out of their respected areas or even flip sides:

![image](https://github.com/LLAMARPG/game/assets/172426161/355ae411-7672-4099-bd90-a16208b15363)

**Comment by Warren1001** [comment]
fixed in 0.1.0

**Comment by Warren1001** [comment]
now live
