### ISSUE TITLE
[Feature] Add a detailed combat log flyout or popup

### ISSUE THREAD

**Issue by Vvnguyen25** [LLAMARPG/game#54]
It would be helpful to understand the calculations of the combat turns. This would help the player understand how the calculations are being done. A player at the end of combat would be able see in full detail of the turn based actions and have a full calculation of what happened during each turn.

**Comment by Warren1001** [comment]
i do intend to break down as much info as i can within combat and on info screens like the character screen/skill tree. this is likely something that will just continuously be improved over the lifespan of the development of the game

i do think having an indicator for crits/glances would be useful asap though
@MrLlamaSC how do you think this should be indicated?

**Comment by MrLlamaSC** [comment]
I think we simply add a small graphic to denote. Should be pretty straight
forward. I'll go come up with something
