### ISSUE TITLE
[Bug] Items can be equipped regardless of stat requirements

### ISSUE THREAD

**Issue by Vvnguyen25** [LLAMARPG/game#56]
**A clear and concise description of what the bug is:**
A player is able to use an item that they do not have the stat for. When a player doesn't have enough stat points, they should not be able to use the item.

1. Take  an item that you do not meet the requirements for and equip it

![image](https://github.com/LLAMARPG/game/assets/172426161/693e2168-6d68-472b-b634-06092ba4b61e)

**Comment by Warren1001** [comment]
not a bug, intended. youre allowed to put unequippable items into equipment slots, but you wont gain any stats for them until you emet the requirements
