### ISSUE TITLE
[Bug] Unable to use any combat actions besides Rest and Escape

### ISSUE THREAD

**Issue by Vvnguyen25** [LLAMARPG/game#57]
**A clear and concise description of what the bug is:**
When in combat, I am unable to select any spells, attacks or defend. 

**Steps to reproduce the behavior, if necessary:**
Go into combat, try and select a spell/attack or defect action.

Here is a few errors from the logs:

USER ERROR: Attempted to use 'has' a variable of type 'int' into a TypedArray of type 'Object'.
   at: ContainerTypeValidate::validate (C:\Godot\godot-4.2.2-stable\core\variant\container_type_validate.h:97)
USER ERROR: Condition "!_p->typed.validate(value, "use 'has'")" is true. Returning: false
   at: Array::has (core\variant\array.cpp:400)
USER ERROR: Attempted to push_back a variable of type 'int' into a TypedArray of type 'Object'.
   at: ContainerTypeValidate::validate (C:\Godot\godot-4.2.2-stable\core\variant\container_type_validate.h:97)
USER ERROR: Condition "!_p->typed.validate(value, "push_back")" is true.
   at: Array::push_back (core\variant\array.cpp:269)

**Comment by Warren1001** [comment]
ya my fix for clicking the acton label by itself was a bit shortsighted, i know how to fix it, itll be fixed tomorrow

**Comment by Warren1001** [comment]
fixed in 0.2.0

**Comment by Warren1001** [comment]
0.2.0 is live
