### ISSUE TITLE
[Bug] When in combat, User to able to spam click the End button to end the battle and the loot items will duplicate.

### ISSUE THREAD

**Issue by Vvnguyen25** [LLAMARPG/game#58]
When in combat and a user hit the End button multiple times, the loot received from the monster will be duplicated.

![image](https://github.com/LLAMARPG/game/assets/172426161/47e38228-54ab-40b0-8b3b-2ff988075410)

1. Enter into combat
2. Click the end button to end the battle multiple times
3. Shown loot will be duplicated and exp/gold will be given for each time clicked.

**Comment by Warren1001** [comment]
not gonna fix since thats a dev feature
