### ISSUE TITLE
[Bug] Unable to discard items in Version 0.2.0

### ISSUE THREAD

**Issue by Vvnguyen25** [LLAMARPG/game#59]
Unable to discard items from inventory in build 0.2.0

1. Drag and drop an item from your inventory
2. Try and discard it.
3. Item remains in hand

**Comment by Warren1001** [comment]
ctrl shift right click

**Comment by Vvnguyen25** [comment]
Ok it worked. Didn't know that was the new command for it. Thank you

**Comment by Vvnguyen25** [comment]
Just one comment, I would put it some where in the settings menu or a place to tell the player how to discard an item.

**Comment by Warren1001** [comment]
yeah, im not sure what to do about this presently. the settings menu is setup in a way that doesnt support multiple keybinds right now, but i could add it there just as info they just wouldnt be able to change it
