### ISSUE TITLE
[Bug] When you have all spells unlocked, the spell action bar in combat overflows to the top of the screen

### ISSUE THREAD

**Issue by Vvnguyen25** [LLAMARPG/game#64]
When a player has all the spells unlocked in game, the spell action bar is unable to display all the spells in the combat actions selection.

1. Level up to get all the spells.
2. Get into combat and select a spell.

Display of all the spells below:
![image](https://github.com/LLAMARPG/game/assets/172426161/5c18cefd-9c86-4bf9-a080-6573a38f33eb)

Maybe have each skill tree have their own column in the action flyout?

**Comment by Warren1001** [comment]
not going to fix, this is unavoidable due to the design, people will have a limited selection of spells that should never be able to take up the full screen
