### ISSUE TITLE
[Feature] Highlight the Combat Menu the player is actively in, to ensure the player is selecting the right counter.

### ISSUE THREAD

**Issue by Vvnguyen25** [LLAMARPG/game#65]
When choosing a counter, the flyout has three options, but display all the same weapons. You only know for sure what you are selecting it when the player has clicked the weapon. Need to have the menus highlighted to show what active path they are in. See screenshot below of mock up:

![image](https://github.com/LLAMARPG/game/assets/172426161/d28d22cc-307f-4933-8d49-44bb84131be1)

**Comment by Warren1001** [comment]
fixed in 0.5.0.0
