### ISSUE TITLE
[Bug] Equipping and Unequipping any Armor items will give a player permanent resistance, stat points and/or def.

### ISSUE THREAD

**Issue by Vvnguyen25** [LLAMARPG/game#68]
Equipping and Unequipping any Armor items will give a player permanent resistance stat points and/or defense that keeps stacking if the player keeps taking the item off and on.

1. Take an item that has elemental resistance and def. 
3. Equip them and Unequip them over and over again.

![image](https://github.com/LLAMARPG/game/assets/172426161/7c7fd063-d861-44db-8084-c927cc5b0aab)

**Comment by Vvnguyen25** [comment]
![image](https://github.com/LLAMARPG/game/assets/172426161/f8b0e47f-269e-46fd-aaba-7fd96fcec9da)
 Just another funny screenshot lol

**Comment by Warren1001** [comment]
LOL wtf
is it only clientside? do these values apply in combat

**Comment by Vvnguyen25** [comment]
Not sure I can check the logs, if they apply in combat. But they do reset if the user leaves the game and comes back.

**Comment by Warren1001** [comment]
well like would you take burn damage with over 100% resistance for example. if you still take burn damage in combat then its client side and i just forgot to remove the stats on unequip only for clientside. if you are immune, its happening for server side too

**Comment by Vvnguyen25** [comment]
Heres an error i found in the logs, not sure if they are related to be honest.

[2024-06-22T07.25.47] ERROR: Failed to execute expression 'FALSE' for reason: Invalid named index 'FALSE' for base type Object
	res://shared/data/file/Formula.gd:25 in function 'evaluate'
	res://shared/data/file/ComplexValue.gd:199 in function 'as_bool'
	res://client/ui/game/inventory/ItemView.gd:159 in function 'set_description_equippable'
	res://client/ui/game/inventory/ItemView.gd:72 in function 'set_description'
	res://client/ui/game/inventory/ItemView.gd:54 in function 'update_display'
	res://client/ui/game/inventory/ItemView.gd:40 in function 'set_item'
	res://client/ui/game/combat/UselessActionButton.gd:15 in function 'set_item'
	res://client/ui/game/combat/CombatLog.gd:137 in function 'process_next'
	res://client/ui/game/combat/CombatLog.gd:87 in function 'finish_processing'
	res://client/ui/game/combat/BattleMode.gd:481 in function '_on_attack_pressed'
USER ERROR: Invalid named index 'FALSE' for base type Object
   at: Expression::execute (core\math\expression.cpp:1507)

I did go into combat found an enemy with cold attacks and burn attacks and they did no damage:

![image](https://github.com/LLAMARPG/game/assets/172426161/754cf5e6-4a06-4510-8e26-045101b50cf7)

![image](https://github.com/LLAMARPG/game/assets/172426161/e7ed42c7-d05e-4e35-ab4d-8b1133dcb7d4)

**Comment by Warren1001** [comment]
fixed in 0.3.0

**Comment by Warren1001** [comment]
0.3.0 is live
