### ISSUE TITLE
[Feature] Elemental Blocking should have an icon shield in the combat log

### ISSUE THREAD

**Issue by Vvnguyen25** [LLAMARPG/game#94]
For the combat log, it would be good to have a shield then the element icon in the combat log to show elemental block damage. So the combat log is easier to read from a glance.

Right now this is how it is:
![image](https://github.com/LLAMARPG/game/assets/172426161/e4d79147-69dc-4525-a792-efc21a2414a0)

**Comment by Warren1001** [comment]
no longer applicable
