### ISSUE TITLE
[Feature] Battle Combat Log should indicate what action what done by Player vs Enemy

### ISSUE THREAD

**Issue by Vvnguyen25** [LLAMARPG/game#98]
The combat log shows the spells of both enemy and player, but it doesn't exactly show what player did what action easily. If both players rest or a spell was done, it doesn't show what order it was done at the end of the turn. So if you were to go back and look at a turn, you wouldn't be able to tell.

It would be best to make an indicator or maybe arrows to show what player did what action.

Poor mock up below:

![image](https://github.com/LLAMARPG/game/assets/172426161/0b60b034-d94f-477d-95cb-933ac6f0222c)

**Comment by Warren1001** [comment]
no longer applicable
